import Image from "next/image";
import dynamic from "next/dynamic";
import type { Metadata } from "next";
import SkeletonHero from "./components/skeletons/SkeletonHero";
import SkeletonAbout from "./components/skeletons/SkeletonAbout";
import SkeletonService from "./components/skeletons/SkeletonService";
import SkeletonSkills from "./components/skeletons/SkeletonSkills";
import SkeletonProject from "./components/skeletons/SkeletonProject";
import SkeletonContact from "./components/skeletons/SkeletonContact";

// Import dynamic components with code splitting and disable server-side rendering (ssr: false).
const Hero = dynamic(() => import("./components/Hero"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonHero />
    </div>
  ),
});
const About = dynamic(() => import("./components/About"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonAbout />
    </div>
  ),
});
const Service = dynamic(() => import("./components/Service"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonService />
    </div>
  ),
});
const Skills = dynamic(() => import("./components/Skills"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonSkills />
    </div>
  ),
});
const Project = dynamic(() => import("./components/Project"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonProject />
    </div>
  ),
});
const Contact = dynamic(() => import("./components/Contact"), {
  ssr: false,
  loading: () => (
    <div>
      <SkeletonContact />
    </div>
  ),
});

// Metadata for your Next.js application
const metadata: Metadata = {
  title: "Create Resume App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="w-full text-white">
      <Hero />

      <About />

      <Service />

      <Skills />

      <Project />

      <Contact />
    </div>
  );
}
